import jsPDF from "jspdf";

const BRAND = { r: 109, g: 76, b: 65 }; // primary
const ACCENT = { r: 166, g: 124, b: 82 };
const INK = { r: 31, g: 31, b: 31 };
const MUTED = { r: 107, g: 107, b: 107 };

export function exportResumeReport(user: any) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const W = doc.internal.pageSize.getWidth();
  const H = doc.internal.pageSize.getHeight();
  const M = 48;
  let y = M;

  // Top brand bar
  doc.setFillColor(BRAND.r, BRAND.g, BRAND.b);
  doc.rect(0, 0, W, 8, "F");

  // Header
  doc.setFont("helvetica", "bold");
  doc.setTextColor(INK.r, INK.g, INK.b);
  doc.setFontSize(22);
  doc.text("Aria · Resume & ATS Report", M, y + 30);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(MUTED.r, MUTED.g, MUTED.b);
  doc.text(new Date().toLocaleDateString(undefined, { year: "numeric", month: "long", day: "numeric" }), M, y + 48);
  y += 76;

  // User block
  doc.setDrawColor(229, 224, 217);
  doc.setFillColor(248, 246, 242);
  doc.roundedRect(M, y, W - M * 2, 70, 10, 10, "FD");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(INK.r, INK.g, INK.b);
  doc.text(user.name || "Job Seeker", M + 18, y + 26);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(MUTED.r, MUTED.g, MUTED.b);
  doc.text(`${user.title || "Software Specialist"} · ${user.location || "Remote"}`, M + 18, y + 44);
  doc.text(user.email || "", M + 18, y + 58);
  y += 90;

  // Scores
  drawSectionLabel(doc, "Scores", M, y);
  y += 22;
  drawScoreCard(doc, M, y, (W - M * 2 - 16) / 2, "Resume strength", user.resumeScore ?? 80, "Top 15% in your field");
  drawScoreCard(doc, M + (W - M * 2 - 16) / 2 + 16, y, (W - M * 2 - 16) / 2, "ATS compatibility", user.atsScore ?? 85, "Parses cleanly across major systems");
  y += 110;

  // Skills detected
  drawSectionLabel(doc, "Skills detected", M, y);
  y += 22;
  y = drawChips(doc, M, y, W - M * 2, user.skills || [], false);
  y += 14;

  // Missing skills
  drawSectionLabel(doc, "Skills that would unlock more roles", M, y);
  y += 22;
  y = drawChips(doc, M, y, W - M * 2, user.missingSkills || [], true);
  y += 14;

  // Recommendations
  drawSectionLabel(doc, "Recommendations", M, y);
  y += 22;
  const recs = user.improvements && user.improvements.length > 0 ? user.improvements : [
    "Quantify impact in your last two roles (revenue, latency, NPS).",
    "Move the skills section above experience for ATS visibility.",
    "Replace passive 'responsible for' phrasing with action verbs.",
    "Add a one-line headline summarizing your specialty + scale.",
  ];
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10.5);
  doc.setTextColor(INK.r, INK.g, INK.b);
  recs.forEach((r: string) => {
    if (y > H - 70) { doc.addPage(); y = M; }
    doc.setFillColor(ACCENT.r, ACCENT.g, ACCENT.b);
    doc.circle(M + 4, y - 4, 2.5, "F");
    const lines = doc.splitTextToSize(r, W - M * 2 - 20) as string[];
    doc.text(lines, M + 16, y);
    y += 14 * lines.length + 6;
  });

  // ATS breakdown
  if (y > H - 200) { doc.addPage(); y = M; }
  y += 8;
  drawSectionLabel(doc, "ATS breakdown", M, y);
  y += 22;
  const breakdown = [
    { k: "Parseable structure", v: 96 },
    { k: "Standard headings", v: 92 },
    { k: "Keyword density", v: 84 },
    { k: "Contact info clarity", v: 100 },
    { k: "File format & fonts", v: 98 },
  ];
  breakdown.forEach((b) => {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(INK.r, INK.g, INK.b);
    doc.text(b.k, M, y);
    doc.setTextColor(MUTED.r, MUTED.g, MUTED.b);
    doc.text(`${b.v}`, W - M, y, { align: "right" });
    const barW = W - M * 2;
    doc.setFillColor(240, 235, 228);
    doc.roundedRect(M, y + 6, barW, 6, 3, 3, "F");
    doc.setFillColor(ACCENT.r, ACCENT.g, ACCENT.b);
    doc.roundedRect(M, y + 6, barW * (b.v / 100), 6, 3, 3, "F");
    y += 28;
  });

  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(9);
    doc.setTextColor(MUTED.r, MUTED.g, MUTED.b);
    doc.text("Generated by Aria — your AI job finder", M, H - 24);
    doc.text(`${i} / ${pageCount}`, W - M, H - 24, { align: "right" });
  }

  doc.save(`aria-resume-report-${Date.now()}.pdf`);
}

function drawSectionLabel(doc: jsPDF, label: string, x: number, y: number) {
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(MUTED.r, MUTED.g, MUTED.b);
  doc.text(label.toUpperCase(), x, y);
  doc.setDrawColor(229, 224, 217);
  doc.line(x, y + 6, x + 360, y + 6);
}

function drawScoreCard(doc: jsPDF, x: number, y: number, w: number, label: string, value: number, sub: string) {
  doc.setDrawColor(229, 224, 217);
  doc.setFillColor(255, 255, 255);
  doc.roundedRect(x, y, w, 92, 10, 10, "FD");
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(MUTED.r, MUTED.g, MUTED.b);
  doc.text(label.toUpperCase(), x + 16, y + 22);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(34);
  doc.setTextColor(ACCENT.r, ACCENT.g, ACCENT.b);
  doc.text(`${value}`, x + 16, y + 58);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(MUTED.r, MUTED.g, MUTED.b);
  doc.text(sub, x + 16, y + 76);
  // ring
  const cx = x + w - 38;
  const cy = y + 46;
  doc.setDrawColor(240, 235, 228);
  doc.setLineWidth(5);
  doc.circle(cx, cy, 22, "S");
  doc.setDrawColor(ACCENT.r, ACCENT.g, ACCENT.b);
  // Arc approximation: draw chord steps
  const steps = Math.max(2, Math.round((value / 100) * 48));
  for (let i = 0; i < steps; i++) {
    const a1 = -Math.PI / 2 + (i / 48) * Math.PI * 2;
    const a2 = -Math.PI / 2 + ((i + 1) / 48) * Math.PI * 2;
    doc.line(cx + 22 * Math.cos(a1), cy + 22 * Math.sin(a1), cx + 22 * Math.cos(a2), cy + 22 * Math.sin(a2));
  }
}

function drawChips(doc: jsPDF, x: number, y: number, maxW: number, items: string[], dashed: boolean): number {
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  let cx = x;
  let cy = y;
  const padX = 10;
  const padY = 5;
  const gap = 6;
  const rowH = 22;
  items.forEach((s) => {
    const label = dashed ? `+ ${s}` : s;
    const tw = doc.getTextWidth(label) + padX * 2;
    if (cx + tw > x + maxW) { cx = x; cy += rowH + gap; }
    if (dashed) {
      doc.setDrawColor(ACCENT.r, ACCENT.g, ACCENT.b);
      doc.setLineDashPattern([3, 3], 0);
      doc.roundedRect(cx, cy, tw, rowH, 11, 11, "S");
      doc.setLineDashPattern([], 0);
      doc.setTextColor(ACCENT.r, ACCENT.g, ACCENT.b);
    } else {
      doc.setFillColor(245, 242, 236);
      doc.roundedRect(cx, cy, tw, rowH, 11, 11, "F");
      doc.setTextColor(INK.r, INK.g, INK.b);
    }
    doc.text(label, cx + padX, cy + rowH / 2 + 3.5);
    cx += tw + gap;
  });
  return cy + rowH;
}
